spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SENTIA
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  logging:
    level:
      root: INFO
      org.springframework.web: INFO
      org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

server:
  port: 8080
